<?php

class DevisePagesSeeder extends DeviseSeeder
{
  public function run()
  {
    $pages = array(
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.pages.index',
        'title'             => 'Manage Pages',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-pages',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages',
        'short_description' => 'Allows the management of devise pages',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.pages.list',
        'title'             => 'JSON List of pages',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-pages-list',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages/list',
        'short_description' => 'Returns a JSON encoded list of pages',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\PageResponseHandler.requestPageList',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.pages.create',
        'title'             => 'Create Page',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-pages-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages/create',
        'short_description' => 'Create a new page',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Store Page',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-pages-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages',
        'short_description' => 'Stores the creation of a new page',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\PageResponseHandler.requestCreateNewPage',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.pages.edit',
        'title'             => 'Edit Page',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-pages-edit',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages/{pageId}/edit',
        'short_description' => 'Edits a page',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update Page',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-pages-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages/{pageId}',
        'short_description' => 'Updates the page record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\PageResponseHandler.requestUpdatePage',
        'response_params'   => 'params.pageId, input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Destroy Page',
        'http_verb'         => 'delete',
        'route_name'        => 'dvs-pages-destroy',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages/{pageId}',
        'short_description' => 'Destroys a page record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\PageResponseHandler.requestDestroyPage',
        'response_params'   => 'params.pageId'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.pages.copy',
        'title'             => 'Copy Page',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-pages-copy',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages/{pageId}/copy',
        'short_description' => 'Copies a page',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Copy Page Store',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-pages-copy-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/pages/{pageId}/copy',
        'short_description' => 'Creates copy record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\PageResponseHandler.requestCopyPage',
        'response_params'   => 'params.pageId, input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.api.index',
        'title'             => 'Manage API Requests',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-api',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/api',
        'short_description' => 'Allows the management of devise API requests',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.api.create',
        'title'             => 'Create API Request Form',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-api-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/api/create',
        'short_description' => 'Create a new API request form',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Store API Request',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-api-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/api',
        'short_description' => 'Stores the data from the API create form',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\ApiPagesResponseHandler.requestCreateNewPage',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.api.edit',
        'title'             => 'Edit API Request Form',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-api-edit',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/api/{pageId}/edit',
        'short_description' => 'Edit an API request form',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update API Request',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-api-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/api/{pageId}',
        'short_description' => 'Updates the API request record using the form data',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\ApiPagesResponseHandler.requestUpdatePage',
        'response_params'   => 'params.pageId, input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Destroy API Request',
        'http_verb'         => 'delete',
        'route_name'        => 'dvs-api-destroy',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/api/{pageId}',
        'short_description' => 'Destroys a page record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\ApiPagesResponseHandler.requestDestroyPage',
        'response_params'   => 'params.pageId'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.content.queue',
        'title'             => 'Content Queue Index',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-content-queue-index',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/content',
        'short_description' => 'Shows all the content currently in the queue',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.users.index',
        'title'             => 'Manage Users',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-users',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/users',
        'short_description' => 'Allows the management of users',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.users.create',
        'title'             => 'Create User',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-users-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/users/create',
        'short_description' => 'Create a new user',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Store User',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-users-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/users',
        'short_description' => 'Stores the creation of a new user',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\UsersResponseHandler.requestCreateUser',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.users.edit',
        'title'             => 'Edit User',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-users-edit',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/users/{userId}/edit',
        'short_description' => 'Edits a user',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update User',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-users-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/users/{userId}',
        'short_description' => 'Updates the user record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\UsersResponseHandler.requestUpdateUser',
        'response_params'   => 'params.userId, input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Destroy User',
        'http_verb'         => 'delete',
        'route_name'        => 'dvs-users-destroy',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/users/{userId}',
        'short_description' => 'Destroys a user record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\UsersResponseHandler.requestDestroyUser',
        'response_params'   => 'params.userId'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.groups.index',
        'title'             => 'Manage Groups',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-groups',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/groups',
        'short_description' => 'Allows the management of groups',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.groups.create',
        'title'             => 'Create Group',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-groups-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/groups/create',
        'short_description' => 'Create a new group',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Store Group',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-groups-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/groups',
        'short_description' => 'Stores the creation of a new group',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\Groups\GroupsResponseHandler.requestCreateGroup',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.groups.edit',
        'title'             => 'Edit User',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-groups-edit',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/groups/{groupId}/edit',
        'short_description' => 'Edits a group',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update Group',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-groups-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/groups/{groupId}',
        'short_description' => 'Updates the group record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\Groups\GroupsResponseHandler.requestUpdateGroup',
        'response_params'   => 'params.groupId, input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Destroy Group',
        'http_verb'         => 'delete',
        'route_name'        => 'dvs-groups-destroy',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/groups/{groupId}',
        'short_description' => 'Destroys a group record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\Groups\GroupsResponseHandler.requestDestroyGroup',
        'response_params'   => 'params.groupId'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.languages.index',
        'title'             => 'All Languages',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-languages',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/languages',
        'short_description' => 'View list of languages',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Toggle Language Enabled',
        'http_verb'         => 'patch',
        'route_name'        => 'dvs-languages-patch',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/languages/{languageId}/patch',
        'short_description' => 'Destroys a group record',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Languages\LanguagesResponseHandler.requestPatchLanguage',
        'response_params'   => 'params.languageId,input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.menus.index',
        'title'             => 'All Menus',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-menus',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/menus',
        'short_description' => 'View list of menus',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.menus.create',
        'title'             => 'Create a new menu',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-menus-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/menus/create',
        'short_description' => 'Create new menu form',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Store menu',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-menus-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/menus',
        'short_description' => 'Store a new menu',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Menus\MenusResponseHandler.requestStore',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.menus.edit',
        'title'             => 'Edit Menu',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-menus-edit',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/menus/{menuId}/edit',
        'short_description' => 'Edit menu',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update a menu',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-menus-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/menus/{menuId}',
        'short_description' => 'Edit existing menu',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Menus\MenusResponseHandler.requestUpdate',
        'response_params'   => 'params.menuId,input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update fields ajaxly',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-fields-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/fields/{fieldId}',
        'short_description' => 'Update a field via ajax call',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Fields\FieldsResponseHandler.requestUpdate',
        'response_params'   => 'params.fieldId,input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Reset field values',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-fields-reset',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/fields/{fieldId}/{fieldScope}/reset',
        'short_description' => 'Reset a field via ajax call',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Fields\FieldsResponseHandler.requestReset',
        'response_params'   => 'params.fieldId,params.fieldScope'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.fields.index',
        'title'             => 'All the Devise fields you could be using',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-fields-index',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/fields',
        'short_description' => 'Shows us the list of devise fields we could be using',
        'response_type'     => 'View'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Mark all content requested for a particular page complete',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-fields-content-requested-mark-all-complete',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/fields/content-requested/{pageId}/mark-complete',
        'short_description' => 'Finds all fields which are flagged as \"content requested\" for all the page versions for a particular page and marks them complete.',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\PageManager.markContentRequestedFieldsComplete',
        'response_params'   => 'params.pageId'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.media.manager',
        'title'             => 'Media Manager',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-media-manager',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager',
        'short_description' => 'User interface for selecting, uploading and managing multi media.'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Handle File Rename',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-media-rename',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager/rename',
        'short_description' => 'Update file name',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Files\ResponseHandler.requestRename',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Handle File Rename',
        'http_verb'         => 'delete',
        'route_name'        => 'dvs-media-remove',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager/remove',
        'short_description' => 'Remove file',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Files\ResponseHandler.requestRemove',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Rename Category',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-media-category-rename',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager/category/rename',
        'short_description' => 'Renames a category',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Categories\ResponseHandler.requestRename',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Handle File Upload',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-media-upload',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager/upload',
        'short_description' => 'Update a field via ajax call',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Files\ResponseHandler.requestUpload',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.media.crop',
        'title'             => 'Media Manager Crop',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-media-crop',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager/crop',
        'short_description' => 'User interface for cropping images.'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Handle Image Crop',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-media-crop-image',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager/crop',
        'short_description' => 'Crop and save new image',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Images\ResponseHandler.requestCrop',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Create New Category',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-media-category-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager/category/store',
        'short_description' => 'Create New Category',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Categories\ResponseHandler.requestStore',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Destroy Category',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-media-category-destroy',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'              => '/admin/media-manager/category/destroy',
        'short_description' => 'Deletes a category',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Categories\ResponseHandler.requestDestroy',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Create collection instance',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-collection-instance-add',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/pages/{pageVersionId}/collections/{collectionSetId}/instances/store',
        'short_description' => 'Adds a new collection instance',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Collections\ResponseHandler.requestStoreInstance',
        'response_params'   => 'params.pageVersionId,params.collectionSetId,input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'List of collections',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-collection-instance-index',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/pages/{pageVersionId}/collections/{collectionSetId}/instances',
        'short_description' => 'Gets a json index of instances',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Collections\CollectionsRepository.getInstances',
        'response_params'   => 'params.pageVersionId,params.collectionSetId'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update instances sort orders',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-collection-instance-update-sort-orders',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/pages/{pageVersionId}/collections/{collectionSetId}/instances/update-sort-orders',
        'short_description' => 'Updates the sort order of a collection',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Collections\ResponseHandler.updateSortOrder',
        'response_params'   => 'params.pageVersionId,params.collectionSetId,input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update collection instance field',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-collection-instance-field-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/collection-fields/{collectionFieldId}',
        'short_description' => "Updates a collection field's values",
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Collections\ResponseHandler.updateCollectionInstanceField',
        'response_params'   => 'params.collectionFieldId,input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Collection update handler',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-collection-instance-update-name',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/pages/{pageVersionId}/collections/{collectionSetId}/instances/{collectionInstanceId}/update-name',
        'short_description' => 'Collection update handler',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Collections\ResponseHandler.renameInstance',
        'response_params'   => 'params.pageVersionId,params.collectionInstanceId,input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Deleting collection instance',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-collection-instance-delete',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/collections/{collectionSetId}/instances/{collectionInstanceId}/delete',
        'short_description' => 'Deletes a collection instance',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Collections\ResponseHandler.requestDeleteInstance',
        'response_params'   => 'params.collectionInstanceId'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => null,
        'title'                   => 'Toggle AB Testing for Page',
        'http_verb'               => 'put',
        'route_name'              => 'dvs-page-ab-testing',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/pages-ab-testing',
        'short_description'       => 'Toggles the ab testing flag for a specific page',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Pages\PageResponseHandler.requestToggleAbTesting',
        'response_params'         => 'input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => null,
        'title'                   => 'Update AB Testing for Page Version',
        'http_verb'               => 'put',
        'route_name'              => 'dvs-update-page-versions-ab-testing',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/pages-versions-ab-testing',
        'short_description'       => 'Update page version ab testing percentage',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Pages\PageResponseHandler.requestUpdatePageVersionAbTesting',
        'response_params'         => 'input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => null,
        'title'                   => 'New Page Version',
        'http_verb'               => 'post',
        'route_name'              => 'dvs-page-version-store',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/page-versions',
        'short_description'       => 'Create a new page version',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Pages\PageResponseHandler.requestStorePageVersion',
        'response_params'         => 'input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => null,
        'title'                   => 'Update Devise Page Version Dates',
        'http_verb'               => 'put',
        'route_name'              => 'dvs-update-page-versions-dates',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/page-versions/{pageVersionId}/dates',
        'short_description'       => 'Updates the starts_at and ends_at dates for a page version',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Pages\PageResponseHandler.requestUpdatePageVersionDates',
        'response_params'         => 'params.pageVersionId,input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => null,
        'title'                   => 'Update Devise Page Version Template',
        'http_verb'               => 'put',
        'route_name'              => 'dvs-update-page-versions-template',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/page-versions/{pageVersionId}/template',
        'short_description'       => 'Updates the template for a page version',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Pages\PageResponseHandler.requestUpdatePageVersionTemplate',
        'response_params'         => 'params.pageVersionId,input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => 'devise::admin.pages.page-versions._card',
        'title'                   => 'Page Versions Card',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-page-versions-card',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/pages/{pageId}/page-versions/card',
        'short_description'       => '',
        'response_type'           => 'View',
        'response_params'         => 'params.pageId'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'title'                   => 'Toggle Sharing Preview URL for a Page Version',
        'http_verb'               => 'put',
        'route_name'              => 'dvs-toggle-page-version-share',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/page-versions/{pageVersionId}/toggle-share',
        'short_description'       => 'Allows admin users to turn on/off the hashed preview url for a page version',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Pages\PageResponseHandler.requestTogglePageVersionShare',
        'response_params'         => 'params.pageVersionId'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'title'                   => 'Deletes a Page Version',
        'http_verb'               => 'delete',
        'route_name'              => 'dvs-delete-page-version',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/page-versions/{pageVersionId}',
        'short_description'       => 'Deletes a page version',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Pages\PageResponseHandler.requestDestroyPageVersion',
        'response_params'         => 'params.pageVersionId'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => 'devise::admin.dashboard.index',
        'title'                   => 'Administration Dashboard',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-dashboard',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin',
        'response_type'           => 'View'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'title'                   => 'Translate Pages',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-translate-all',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/pages/translate/all',
        'short_description'       => '',
        'response_type'           => 'Function',
        'response_path'           => 'Atlantis\Pages\ResponseHandler.copyAllToLanguage'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => 'devise::admin.users.login',
        'title'                   => 'Admin Users Login',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-user-login',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifLoggedInGoToDash',
        'slug'                    => '/admin/login',
        'short_description'       => 'Allows users to login',
        'response_type'           => 'View'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'title'                   => 'User Attempt Login',
        'http_verb'               => 'post',
        'route_name'              => 'dvs-user-attempt-login',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => '',
        'slug'                    => '/admin/attempt-login',
        'short_description'       => 'Attempt to login user',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Users\UsersResponseHandler.requestLogin',
        'response_params'         => 'input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'title'                   => 'User Logout',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-user-logout',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => '',
        'slug'                    => '/admin/logout',
        'short_description'       => 'Allows users to logout',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Users\UsersResponseHandler.requestLogout'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => 'devise::admin.users.forgot',
        'title'                   => 'Admin Users Forgot Password',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-user-recover-password',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifLoggedInGoToDash',
        'slug'                    => '/admin/recover-password',
        'short_description'       => 'Allows users which have forgotten password to recover vai email address',
        'response_type'           => 'View'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'title'                   => 'User Password Recovery',
        'http_verb'               => 'post',
        'route_name'              => 'dvs-user-attempt-recover',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => '',
        'slug'                    => '/admin/attempt-recover',
        'short_description'       => 'Password recovery using user email address',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Users\UsersResponseHandler.requestRecoverPassword',
        'response_params'         => 'input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => 'devise::admin.users.reset',
        'title'                   => 'User Reset Password',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-user-reset-password',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifLoggedInGoToDash',
        'slug'                    => '/admin/reset-password',
        'short_description'       => 'Allows users which have forgotten password to recover vai email address',
        'response_type'           => 'View'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'title'                   => 'User Attempt Password Reset',
        'http_verb'               => 'post',
        'route_name'              => 'dvs-user-attempt-reset',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => '',
        'slug'                    => '/admin/attempt-reset',
        'short_description'       => 'Attempt to reset password',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Users\UsersResponseHandler.requestResetPassword',
        'response_params'         => 'input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => 'devise::admin.users.register',
        'title'                   => 'User Registration',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-user-register',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/register',
        'short_description'       => 'Allows new users to register',
        'response_type'           => 'View'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'title'                   => 'User Attempt Register',
        'http_verb'               => 'post',
        'route_name'              => 'user-attempt-register',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => '',
        'slug'                    => '/admin/attempt-register',
        'short_description'       => 'Attempt to register new user',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Users\UsersResponseHandler.requestRegister',
        'response_params'         => 'input'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => '',
        'title'                   => 'User Activation',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-user-activate',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifLoggedInGoToDash',
        'slug'                    => '/admin/activate/{userId}/{activateCode}',
        'short_description'       => 'Route used to activate a newly registered user',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Users\UsersResponseHandler.requestActivation',
        'response_params'         => 'params.userId,params.activateCode'
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => 'devise::admin.calendar.index',
        'title'                   => 'Devise Admin Calendar that keeps up with different scheduled events',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-calendar-index',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/calendar',
        'short_description'       => 'Shows the calendar for devise admin where we can change schedules',
        'response_type'           => 'View',
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => null,
        'title'                   => 'Devise Admin Calendar Source for Page Versions',
        'http_verb'               => 'get',
        'route_name'              => 'dvs-calendar-page-version-source',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/calendar/sources/page-versions',
        'short_description'       => 'Shows the json data for page versions event source',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Calendar\CalendarResponseHandler.requestPageVersionEventSource',
        'response_params'         => 'input',
      ),
      array(
        'language_id'             => '45',
        'translated_from_page_id' => '0',
        'view'                    => null,
        'title'                   => 'Patches Devise Admin Calendar Source for Page Versions',
        'http_verb'               => 'patch',
        'route_name'              => 'dvs-calendar-page-version-source-update',
        'is_admin'                => '1',
        'dvs_admin'               => '1',
        'middleware'              => 'devise.permissions:ifNotLoggedInGoToLogin',
        'slug'                    => '/admin/calendar/sources/page-versions/{pageVersionId}',
        'short_description'       => 'Updates the page versions dates and information',
        'response_type'           => 'Function',
        'response_path'           => 'Devise\Calendar\CalendarResponseHandler.requestPageVersionEventUpdate',
        'response_params'         => 'params.pageVersionId,input',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.templates.index',
        'title'             => 'Devise Admin Templates',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-templates',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates',
        'short_description' => 'Allows the management of devise templates',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.templates.edit',
        'title'             => 'Admin Edit Template',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-templates-edit',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates/{templatePath}/edit',
        'short_description' => 'Edit a Template',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Admin Update Template',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-templates-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates/{templatePath}',
        'short_description' => 'Attempts to update a template',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Templates\TemplatesResponseHandler.executeUpdate',
        'response_params'   => 'params.templatePath,input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Admin Clean Template Fields',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-templates-clean',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates/clean/{templatePath}',
        'short_description' => 'Attempts to clean old fields from a template',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Templates\TemplatesResponseHandler.executeFieldCleanup',
        'response_params'   => 'params.templatePath'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Destroy Template',
        'http_verb'         => 'delete',
        'route_name'        => 'dvs-templates-destroy',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates/{templatePath}',
        'short_description' => 'Destroys a template',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Templates\TemplatesResponseHandler.executeDestroy',
        'response_params'   => 'params.templatePath'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.templates.params.create',
        'title'             => 'Add Parameter to Template Variable',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-templates-param-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates/params/create/{varName?}',
        'short_description' => 'Add/Create New Parameter for Template Variable',
        'response_params'   => 'params.varName'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.templates.register',
        'title'             => 'Admin Register New Template',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-templates-register',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates/register',
        'short_description' => 'Register a Template',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Admin Store Template',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-templates-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates',
        'short_description' => 'Attempts to store a new template',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Templates\TemplatesResponseHandler.executeStore',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.templates.variables.create',
        'title'             => 'Create New Variable for a Template',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-templates-var-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates/vars/create/{templatePath}',
        'short_description' => 'Create/Add new variable to an existing template',
        'response_params'   => 'params.templatePath'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Store Variable',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-templates-var-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/templates/vars/store/{templatePath}',
        'short_description' => 'Attempt to store a new variable for a template path',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Templates\TemplatesResponseHandler.executeVariableStore',
        'response_params'   => 'params.templatePath,input',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.permissions.index',
        'title'             => 'Devise Admin Permissions',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-permissions',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/permissions',
        'short_description' => 'Allows The Management of Permissions',
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.permissions.create',
        'title'             => 'Admin Create New Permission',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-permissions-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/permissions/create',
        'short_description' => 'Admin Create a New Permission Condition',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Admin Store Permission',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-permissions-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/permissions',
        'short_description' => 'Attempts to Store a New Permission Condition',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\Permissions\PermissionsResponseHandler.executeStore',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'view'              => 'devise::admin.permissions.edit',
        'title'             => 'Admin Edit Permission',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-permissions-edit',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/permissions/edit',
        'short_description' => 'Edit a Permission Condition',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Admin Update Permission',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-permissions-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/permissions/update',
        'short_description' => 'Attempts to Update a Permission Condition',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\Permissions\PermissionsResponseHandler.executeUpdate',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Destroy Permission',
        'http_verb'         => 'delete',
        'route_name'        => 'dvs-permissions-destroy',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/permissions/destroy',
        'short_description' => 'Destroys a Permission Condition',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Users\Permissions\PermissionsResponseHandler.executeDestroy',
        'response_params'   => 'input.condition'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Settings Page',
        'http_verb'         => 'get',
        'view'              => 'devise::admin.settings.index',
        'route_name'        => 'dvs-settings-index',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/settings',
        'short_description' => 'Configure devise settings',
        'response_type'     => 'View',
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Change devise configuration settings',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-settings-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => 'admin/settings',
        'short_description' => 'Updates the devise configuration settings',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Support\Config\SettingsResponseHandler.executeUpdate',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Create a new model managed by DvsModelField',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-model-fields-create',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => 'admin/model-fields',
        'short_description' => 'Create a new model managed by DvsModelField',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Models\ModelsResponseHandler.executeModelFieldsCreate',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update multiple model fields at one time that are managed by DvsModelField',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-model-fields-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => 'admin/model-fields',
        'short_description' => 'Update multiple model fields as one time that are managed by DvsModelField',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Models\ModelsResponseHandler.executeModelFieldsUpdate',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Update a single model field that is managed by a DvsModelField',
        'http_verb'         => 'put',
        'route_name'        => 'dvs-model-field-update',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => 'admin/model-field/{modelFieldId}',
        'short_description' => '',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Pages\Models\ModelsResponseHandler.executeModelFieldUpdate',
        'response_params'   => 'params.modelFieldId,input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'You Have Arrived',
        'view'              => 'homepage',
        'http_verb'         => 'get',
        'route_name'        => 'homepage',
        'is_admin'          => '0',
        'dvs_admin'         => '0',
        'middleware'        => '',
        'slug'              => '/',
        'short_description' => 'A welcome page and example to see how pages work',
        'response_type'     => 'View'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Admin Model Creator',
        'view'              => 'devise::admin.models.create',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-model-creator',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:ifNotLoggedInGoToLogin|devise.permissions:isDeveloper',
        'slug'              => '/admin/models/create',
        'short_description' => 'Create New Model Form',
        'response_type'     => 'View'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Model Creator Store Request',
        'http_verb'         => 'post',
        'route_name'        => 'dvs-model-creator-store',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:isDeveloper',
        'slug'              => '/admin/models',
        'short_description' => 'Admin Model Creator Attempt Store',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Models\Scaffolding\ScaffoldingResponseHandler.requestCreateNewModel',
        'response_params'   => 'input'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Media Manager API: Directories',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-mm-directories',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/api/media-manager/directories/{folder_dot_path?}',
        'short_description' => '',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Response.getDirectories',
        'response_params'   => 'params.folder_dot_path'
      ),
      array(
        'language_id'       => '45',
        'title'             => 'Media Manager API: Files',
        'http_verb'         => 'get',
        'route_name'        => 'dvs-mm-files',
        'is_admin'          => '1',
        'dvs_admin'         => '1',
        'middleware'        => 'devise.permissions:canUseDeviseEditor',
        'slug'              => '/admin/api/media-manager/files/{folder_dot_path?}',
        'short_description' => '',
        'response_type'     => 'Function',
        'response_path'     => 'Devise\Media\Response.getFiles',
        'response_params'   => 'params.folder_dot_path'
      ),
    );

    $now = date('Y-m-d H:i:s', strtotime('now'));

    $dvsPages = $this->findOrCreateRows('dvs_pages', ['http_verb', 'slug'], $pages);

    foreach ($dvsPages as $dvsPage)
    {
      $this->findOrCreateRow('dvs_page_versions', 'page_id', [
        'page_id'            => $dvsPage->id,
        'created_by_user_id' => 1,
        'name'               => 'Default',
        'starts_at'          => $now,
      ]);
    }
  }

}
