<?php

class DevisePagesSeeder extends Seeder
{
	/**
     *
     */
    public function run()
    {
		DB::table( 'dvs_pages' )->delete();
        DB::table( 'dvs_page_versions' )->delete();

		$pages = array(
            array(
				'id'                      => '1',
				'language_id'             => '45',
				'view'                    => 'devise::admin.pages.index',
				'title'                   => 'Manage Pages',
				'http_verb'               => 'get',
				'route_name'              => 'dvs-pages',
				'published'               => '1',
				'is_admin'                => '1',
				'dvs_admin'               => '1',
				'slug'                    => '/admin/pages',
				'short_description'       => 'Allows the management of devise pages',
			),
            array(
                'id'                      => '2',
                'language_id'             => '45',
                'view'                    => 'devise::admin.pages.create',
                'title'                   => 'Create Page',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-pages-create',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/pages/create',
                'short_description'       => 'Create a new page',
            ),
            array(
                'id'                      => '3',
                'language_id'             => '45',
                'title'                   => 'Store Page',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-pages-store',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/pages',
                'short_description'       => 'Stores the creation of a new page',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Pages\PageResponseHandler.requestCreateNewPage',
                'response_params'         => 'input'
            ),
            array(
                'id'                      => '4',
                'language_id'             => '45',
                'view'                    => 'devise::admin.pages.edit',
                'title'                   => 'Edit Page',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-pages-edit',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/pages/{pageId}/edit',
                'short_description'       => 'Edits a page',
            ),
            array(
                'id'                      => '5',
                'language_id'             => '45',
                'title'                   => 'Update Page',
                'http_verb'               => 'put',
                'route_name'              => 'dvs-pages-update',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/pages/{pageId}',
                'short_description'       => 'Updates the page record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Pages\PageResponseHandler.requestUpdatePage',
                'response_params'         => 'params.pageId, input'
            ),
            array(
                'id'                      => '6',
                'language_id'             => '45',
                'title'                   => 'Destroy Page',
                'http_verb'               => 'delete',
                'route_name'              => 'dvs-pages-destroy',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/pages/{pageId}',
                'short_description'       => 'Destroys a page record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Pages\PageResponseHandler.requestDestroyPage',
                'response_params'         => 'params.pageId'
            ),
            array(
                'id'                      => '7',
                'language_id'             => '45',
                'view'                    => 'devise::admin.pages.copy',
                'title'                   => 'Copy Page',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-pages-copy',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/pages/{pageId}/copy',
                'short_description'       => 'Copies a page',
            ),
            array(
                'id'                      => '8',
                'language_id'             => '45',
                'title'                   => 'Copy Page Store',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-pages-copy-store',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/pages/{pageId}/copy',
                'short_description'       => 'Creates copy record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Pages\PageResponseHandler.requestCopyPage',
                'response_params'         => 'params.pageId, input'
            ),
			array(
				'id'                      => '9',
				'language_id'             => '45',
				'title'                   => 'Partial Loader',
				'http_verb'               => 'post',
				'route_name'              => 'dvs-partials',
				'published'               => '1',
				'is_admin'                => '1',
				'dvs_admin'               => '1',
				'slug'                    => '/admin/partials/sidebar',
				'short_description'       => 'Loads a partial for an AJAX load',
				'response_type'           => 'Function',
				'response_path'           => 'Devise\Sidebar\ResponseHandler.requestSidebarPartial',
				'response_params'         => 'input'
			),
            array(
                'id'                      => '20',
                'language_id'             => '45',
                'view'                    => 'devise::admin.templates.index',
                'title'                   => 'Templates Index',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-templates',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/templates',
                'short_description'       => 'Allows the management of all the templates',
            ),
            array(
                'id'                      => '21',
                'language_id'             => '45',
                'view'                    => 'devise::admin.templates.upload',
                'title'                   => 'Upload New Template',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-templates-upload',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/templates/upload',
                'short_description'       => 'Upload a new template',
            ),
            array(
                'id'                      => '22',
                'language_id'             => '45',
                'view'                    => 'devise::admin.templates.review',
                'title'                   => 'Review Template',
                'http_verb'               => 'any',
                'route_name'              => 'dvs-templates-review',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/templates/review',
                'short_description'       => 'Review a template ',
            ),
            array(
                'id'                      => '23',
                'language_id'             => '45',
                'title'                   => 'Store Template',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-templates-store',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/templates',
                'short_description'       => 'Stores a new template',
            ),
            array(
                'id'                      => '24',
                'language_id'             => '45',
                'view'                    => 'devise::admin.templates.edit',
                'title'                   => 'Edit Template',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-templates-edit',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/templates/{templateId}/edit',
                'short_description'       => 'Edit a Template',
            ),
            array(
                'id'                      => '25',
                'language_id'             => '45',
                'title'                   => 'Update Template',
                'http_verb'               => 'put',
                'route_name'              => 'dvs-templates-update',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/templates/{templateId}',
                'short_description'       => 'Attempts to update a template',
            ),
            array(
                'id'                      => '26',
                'language_id'             => '45',
                'title'                   => 'Destroy Template',
                'http_verb'               => 'delete',
                'route_name'              => 'dvs-templates-destroy',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/templates/{templateId}',
                'short_description'       => 'Destroys a template',
            ),
            array(
                'id'                      => '30',
                'language_id'             => '45',
                'view'                    => 'devise::admin.content.queue',
                'title'                   => 'Content Queue Index',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-content-queue-index',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/content',
                'short_description'       => 'Shows all the content currently in the queue',
            ),
            array(
                'id'                      => '40',
                'language_id'             => '45',
                'view'                    => 'devise::admin.users.index',
                'title'                   => 'Manage Users',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-users',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/users',
                'short_description'       => 'Allows the management of users',
            ),
            array(
                'id'                      => '41',
                'language_id'             => '45',
                'view'                    => 'devise::admin.users.create',
                'title'                   => 'Create User',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-users-create',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/users/create',
                'short_description'       => 'Create a new user',
            ),
            array(
                'id'                      => '42',
                'language_id'             => '45',
                'title'                   => 'Store User',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-users-store',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/users',
                'short_description'       => 'Stores the creation of a new user',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Users\UsersResponseHandler.requestCreateUser',
                'response_params'         => 'input'
            ),
            array(
                'id'                      => '43',
                'language_id'             => '45',
                'view'                    => 'devise::admin.users.edit',
                'title'                   => 'Edit User',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-users-edit',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/users/{userId}/edit',
                'short_description'       => 'Edits a user',
            ),
            array(
                'id'                      => '44',
                'language_id'             => '45',
                'title'                   => 'Update User',
                'http_verb'               => 'put',
                'route_name'              => 'dvs-users-update',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/users/{userId}',
                'short_description'       => 'Updates the user record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Users\UsersResponseHandler.requestUpdateUser',
                'response_params'         => 'params.userId, input'
            ),
            array(
                'id'                      => '45',
                'language_id'             => '45',
                'title'                   => 'Destroy User',
                'http_verb'               => 'delete',
                'route_name'              => 'dvs-users-destroy',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/users/{userId}',
                'short_description'       => 'Destroys a user record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Users\UsersResponseHandler.requestDestroyUser',
                'response_params'         => 'params.userId'
            ),
            array(
                'id'                      => '50',
                'language_id'             => '45',
                'view'                    => 'devise::admin.groups.index',
                'title'                   => 'Manage Groups',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-groups',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/groups',
                'short_description'       => 'Allows the management of groups',
            ),
            array(
                'id'                      => '51',
                'language_id'             => '45',
                'view'                    => 'devise::admin.groups.create',
                'title'                   => 'Create Group',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-groups-create',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/groups/create',
                'short_description'       => 'Create a new group',
            ),
            array(
                'id'                      => '52',
                'language_id'             => '45',
                'title'                   => 'Store Group',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-groups-store',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/groups',
                'short_description'       => 'Stores the creation of a new group',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Users\Groups\GroupsResponseHandler.requestCreateGroup',
                'response_params'         => 'input'
            ),
            array(
                'id'                      => '53',
                'language_id'             => '45',
                'view'                    => 'devise::admin.groups.edit',
                'title'                   => 'Edit User',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-groups-edit',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/groups/{groupId}/edit',
                'short_description'       => 'Edits a group',
            ),
            array(
                'id'                      => '54',
                'language_id'             => '45',
                'title'                   => 'Update Group',
                'http_verb'               => 'put',
                'route_name'              => 'dvs-groups-update',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/groups/{groupId}',
                'short_description'       => 'Updates the group record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Users\Groups\GroupsResponseHandler.requestUpdateGroup',
                'response_params'         => 'params.groupId, input'
            ),
            array(
                'id'                      => '55',
                'language_id'             => '45',
                'title'                   => 'Destroy Group',
                'http_verb'               => 'delete',
                'route_name'              => 'dvs-groups-destroy',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/groups/{groupId}',
                'short_description'       => 'Destroys a group record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Users\Groups\GroupsResponseHandler.requestDestroyGroup',
                'response_params'         => 'params.groupId'
            ),
            array(
                'id'                      => '56',
                'language_id'             => '45',
                'view'                    => 'devise::admin.languages.index',
                'title'                   => 'All Languages',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-languages',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/languages',
                'short_description'       => 'View list of languages',
            ),
            array(
                'id'                      => '57',
                'language_id'             => '45',
                'title'                   => 'Toggle Language Enabled',
                'http_verb'               => 'patch',
                'route_name'              => 'dvs-languages-patch',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/languages/{languageId}/patch',
                'short_description'       => 'Destroys a group record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Languages\LanguagesResponseHandler.requestPatchLanguage',
                'response_params'         => 'params.languageId,input'
            ),
            array(
                'id'                      => '58',
                'language_id'             => '45',
                'view'                    => 'devise::admin.menus.index',
                'title'                   => 'All Menus',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-menus',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/menus',
                'short_description'       => 'View list of menus',
            ),
            array(
                'id'                      => '59',
                'language_id'             => '45',
                'title'                   => 'Create a new menu',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-menus-store',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/menus',
                'short_description'       => 'Create a new menu to edit',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Menus\MenusResponseHandler.requestStore',
                'response_params'         => 'input'
            ),
            array(
                'id'                      => '60',
                'language_id'             => '45',
                'view'                    => 'devise::admin.menus.edit',
                'title'                   => 'Edit Menu',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-menus-edit',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/menus/{menuId}/edit',
                'short_description'       => 'Edit menu',
            ),
            array(
                'id'                      => '61',
                'language_id'             => '45',
                'title'                   => 'Update a menu',
                'http_verb'               => 'put',
                'route_name'              => 'dvs-menus-update',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/menus/{menuId}',
                'short_description'       => 'Edit existing menu',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Menus\MenusResponseHandler.requestUpdate',
                'response_params'         => 'params.menuId,input'
            ),
            array(
                'id'                      => '62',
                'language_id'             => '45',
                'title'                   => 'Update fields ajaxly',
                'http_verb'               => 'put',
                'route_name'              => 'dvs-fields-update',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/fields/{fieldId}',
                'short_description'       => 'Update a field via ajax call',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Pages\Fields\FieldsResponseHandler.requestUpdate',
                'response_params'         => 'params.fieldId,input'
            ),
            array(
                'id'                      => '63',
                'language_id'             => '45',
                'view'                    => 'devise::admin.media.manager',
                'title'                   => 'Media Manager',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-media-manager',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/media-manager',
                'short_description'       => 'User interface for selecting, uploading and managing multi media.'
            ),
            array(
                'id'                      => '64',
                'language_id'             => '45',
                'title'                   => 'Handle File Upload',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-media-upload',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/media-manager/upload',
                'short_description'       => 'Update a field via ajax call',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Media\Files\ResponseHandler.requestUpload',
                'response_params'         => 'input'
            ),
            array(
                'id'                      => '65',
                'language_id'             => '45',
                'view'                    => 'devise::admin.media.crop',
                'title'                   => 'Media Manager Crop',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-media-crop',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/media-manager/crop',
                'short_description'       => 'User interface for cropping images.'
            ),
            array(
                'id'                      => '66',
                'language_id'             => '45',
                'title'                   => 'Handle Image Crop',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-media-crop-image',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/media-manager/crop',
                'short_description'       => 'Crop and save new image',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Media\Images\ResponseHandler.requestCrop',
                'response_params'         => 'input'
            ),
            array(
                'id'                      => '67',
                'language_id'             => '45',
                'title'                   => 'Create New Category',
                'http_verb'               => 'post',
                'route_name'              => 'dvs-media-category-store',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/media-manager/category/store',
                'short_description'       => 'Create New Category',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Media\Categories\ResponseHandler.requestStore',
                'response_params'         => 'input'
            ),
            array(
                'id'                      => '68',
                'language_id'             => '45',
                'title'                   => 'Destroy Category',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-media-category-destroy',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/media-manager/category/destroy',
                'short_description'       => 'Deletes a category',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Media\Categories\ResponseHandler.requestDestroy',
                'response_params'         => 'input'
            ),
			array(
				'id'                      => '70',
				'language_id'             => '45',
				'title'                   => 'Create collection instance',
				'http_verb'               => 'post',
				'route_name'              => 'dvs-collection-instance-add',
				'published'               => '1',
				'is_admin'                => '1',
				'dvs_admin'               => '1',
				'slug'                    => '/admin/collections/{collectionSetId}/instances/store',
				'short_description'       => 'Adds a new collection instance',
				'response_type'           => 'Function',
				'response_path'           => 'Devise\Pages\Collections\ResponseHandler.requestStoreInstance',
				'response_params'         => 'params.collectionSetId,input'
			),
			array(
				'id'                      => '71',
				'language_id'             => '45',
				'title'                   => 'Get collection instances',
				'http_verb'               => 'get',
				'route_name'              => 'dvs-collection-instance-index',
				'published'               => '1',
				'is_admin'                => '1',
				'dvs_admin'               => '1',
				'slug'                    => '/admin/collections/{collectionSetId}/instances',
				'short_description'       => 'Gets a json index of instances',
				'response_type'           => 'Function',
				'response_path'           => 'Devise\Pages\Collections\CollectionsRepository.getInstances',
				'response_params'         => 'params.collectionSetId'
			),
			array(
				'id'                      => '72',
				'language_id'             => '45',
				'title'                   => 'Update instances sort orders',
				'http_verb'               => 'post',
				'route_name'              => 'dvs-collection-instance-update-sort-orders',
				'published'               => '1',
				'is_admin'                => '1',
				'dvs_admin'               => '1',
				'slug'                    => '/admin/collections/{collectionSetId}/instances/update-sort-orders',
				'short_description'       => 'Updates the sort order of a collection',
				'response_type'           => 'Function',
				'response_path'           => 'Devise\Pages\Collections\ResponseHandler.updateSortOrder',
				'response_params'         => 'params.collectionSetId,input'
			),
			array(
				'id'                      => '73',
				'language_id'             => '45',
				'title'                   => 'Update instance name',
				'http_verb'               => 'put',
				'route_name'              => 'dvs-collection-instance-update-name',
				'published'               => '1',
				'is_admin'                => '1',
				'dvs_admin'               => '1',
				'slug'                    => '/admin/collections/{collectionSetId}/instances/{collectionInstanceId}/update-name',
				'short_description'       => 'Updates the name of an instance',
				'response_type'           => 'Function',
				'response_path'           => 'Devise\Pages\Collections\ResponseHandler.renameInstance',
				'response_params'         => 'params.collectionInstanceId,input'
			),
            array(
                'id'                      => '74',
                'language_id'             => '45',
                'translated_from_page_id' => '0',
                'view'                    => null,
                'title'                   => 'Destroy Page Version',
                'http_verb'               => 'delete',
                'route_name'              => 'dvs-page-version-destroy',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/page-versions/{pageVersionId}',
                'short_description'       => 'Destroys a page version record',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Pages\PageResponseHandler.requestDestroyPageVersion',
                'response_params'         => 'params.pageVersionId'
            ),
            array(
                'id'                      => '75',
                'language_id'             => '45',
                'translated_from_page_id' => '0',
                'view'                    => null,
                'title'                   => 'Update Devise Page Version Dates',
                'http_verb'               => 'put',
                'route_name'              => 'dvs-update-page-versions-dates',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '0',
                'slug'                    => '/admin/page-versions/{pageVersionId}/dates',
                'short_description'       => 'Updates the starts_at and ends_at dates for a page version',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Pages\PageResponseHandler.requestUpdatePageVersionDates',
                'response_params'         => 'params.pageVersionId,input'
            ),
            array(
                'id'                      => '76',
                'language_id'             => '45',
                'translated_from_page_id' => '0',
                'view'                    => 'devise::admin.pages.page-versions._card',
                'title'                   => 'Page Versions Card',
                'http_verb'               => 'get',
                'route_name'              => 'dvs-page-versions-card',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/pages/{pageId}/page-versions/card',
                'short_description'       => '',
                'response_type'           => 'View',
                'response_params'         => 'params.pageId'
            ),
            array(
                'id'                      => '77',
                'language_id'             => '45',
                'translated_from_page_id' => '0',
                'view'                    => null,
                'title'                   => 'Toggle Sharing Preview URL for a Page Version',
                'http_verb'               => 'put',
                'route_name'              => 'dvs-toggle-page-version-share',
                'published'               => '1',
                'is_admin'                => '1',
                'dvs_admin'               => '1',
                'slug'                    => '/admin/page-versions/{pageVersionId}/toggle-share',
                'short_description'       => 'Allows admin users to turn on/off the hashed preview url for a page version',
                'response_type'           => 'Function',
                'response_path'           => 'Devise\Pages\PageResponseHandler.requestTogglePageVersionShare',
                'response_params'         => 'params.pageVersionId'
            ),
		);

		foreach ( $pages as $page )
        {
            $page['created_at'] = date('Y-m-d H:i:s', strtotime('now'));
            $page['updated_at'] = date('Y-m-d H:i:s', strtotime('now'));
			DB::table( 'dvs_pages' )->insert( array( $page ) );
            DB::table( 'dvs_page_versions' )->insert(
            [
                'id' => $page['id'],
                'page_id' => $page['id'],
                'created_by_user_id' => 1,
                'name' => 'Default',
            ]);
		}
	}

}
