<?php
return array(

    'groups' => array(
        'model_1' => 'User',
        'model_2' => 'Group',
        'type' => 'belongsToMany',
        'foreign_key' => '',
        'pivot_table' => 'group_user',
        'pivot_key_model_1' => 'user_id',
        'pivot_key_model_2' => 'group_id',
    ),

    'users' => array(
        'model_1' => 'Group',
        'model_2' => 'User',
        'type' => 'belongsToMany',
        'foreign_key' => '',
        'pivot_table' => 'group_user',
        'pivot_key_model_1' => 'group_id',
        'pivot_key_model_2' => 'user_id',
    ),

    'car_factory' => array(
        'model_1' => 'Car',
        'model_2' => 'Factory',
        'type' => 'belongsTo',
        'foreign_key' => 'factory_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),

    'car_owner' => array(
        'model_1' => 'Car',
        'model_2' => 'Owner',
        'type' => 'belongsTo',
        'foreign_key' => 'owner_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),

    'factory_district' => array(
        'model_1' => 'Factory',
        'model_2' => 'District',
        'type' => 'belongsTo',
        'foreign_key' => 'district_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),
    'factory' => array(
        'model_1' => 'Car',
        'model_2' => 'Factory',
        'type' => 'belongsTo',
        'foreign_key' => 'factory_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),
    'cars' => array(
        'model_1' => 'Factory',
        'model_2' => 'Car',
        'type' => 'hasMany',
        'foreign_key' => 'factory_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),
    'district' => array(
        'model_1' => 'Factory',
        'model_2' => 'District',
        'type' => 'belongsTo',
        'foreign_key' => 'district_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),
    'factories' => array(
        'model_1' => 'District',
        'model_2' => 'Factory',
        'type' => 'hasMany',
        'foreign_key' => 'district_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),
    'colors' => array(
        'model_1' => 'Car',
        'model_2' => 'Color',
        'type' => 'belongsToMany',
        'foreign_key' => '',
        'pivot_table' => 'car_color',
        'pivot_key_model_1' => 'car_id',
        'pivot_key_model_2' => 'color_id',
    ),
    'colorscars' => array(
        'model_1' => 'Color',
        'model_2' => 'Car',
        'type' => 'belongsToMany',
        'foreign_key' => '',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),
    'owner' => array(
        'model_1' => 'Car',
        'model_2' => 'Owner',
        'type' => 'belongsTo',
        'foreign_key' => 'owner_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),
    'car' => array(
        'model_1' => 'Owner',
        'model_2' => 'Car',
        'type' => 'hasOne',
        'foreign_key' => 'owner_id',
        'pivot_table' => '',
        'pivot_key_model_1' => '',
        'pivot_key_model_2' => '',
    ),

);